import React,{useEffect,useMemo,useRef,useState}from"react";
import{createRoot}from"react-dom/client";
import{Client,handle_file}from"@gradio/client";
import{Upload,Play,Download,RefreshCw,Film,Sparkles,Check,Loader2,Clapperboard,Settings2,AlertTriangle,ChevronDown,ChevronUp,Copy,SlidersHorizontal, WandSparkles}from"lucide-react";
import"./styles.css";

const MODEL="fal-ai/kling-video/v3/standard/image-to-video";
const cameraMoves=["locked hero push-in","slow lateral slide","macro texture drift","smooth overhead reveal","controlled 360 orbit","low-angle rise","diagonal tracking move","locked closing frame"];
const baseShots=[
 {name:"Hero opener",action:"The product stands centered as a few established product-related elements enter the frame with precise, energetic timing.",camera:"locked hero push-in"},
 {name:"Material detail",action:"A tight macro view reveals the product surface, texture, finish and authentic physical details.",camera:"macro texture drift"},
 {name:"Action moment",action:"A believable hand or environmental action interacts with the product without changing its identity or packaging.",camera:"slow lateral slide"},
 {name:"Transformation cut",action:"A hard editorial cut changes the action while keeping the same lighting and framing; no morphing or melting.",camera:"smooth overhead reveal"},
 {name:"Dynamic product",action:"The product performs a restrained physical movement while remaining structurally consistent.",camera:"low-angle rise"},
 {name:"Hero orbit",action:"The camera makes a smooth cinematic orbit around the product without distortion.",camera:"controlled 360 orbit"},
 {name:"Detail payoff",action:"One final premium detail is revealed with realistic depth, light and subtle motion.",camera:"diagonal tracking move"},
 {name:"Closing packshot",action:"The product settles centered and resolved in a clean commercial hero frame.",camera:"locked closing frame"}
];

function selectedMotionText(style,motion,intensity){return `Professional product commercial, ${style}, ${motion} camera movement, motion intensity ${intensity}%, physically plausible movement, preserve exact product identity, packaging and visible text.`}

function App(){
 const[file,setFile]=useState(null),[preview,setPreview]=useState(""),[playableVideo,setPlayableVideo]=useState(""),[brief,setBrief]=useState("Create a premium cinematic product advertisement. Preserve the exact product identity, packaging, proportions, materials and visible text. Use realistic commercial lighting, elegant depth, physically plausible motion and clean editorial cuts. Nothing should be invented that conflicts with the reference image.");
 const[aspect,setAspect]=useState("9:16"),[duration,setDuration]=useState(5),[plan,setPlan]=useState(null),[busy,setBusy]=useState(false),[video,setVideo]=useState(""),[status,setStatus]=useState(""),[error,setError]=useState(""),[settings,setSettings]=useState(true),[style,setStyle]=useState("Luxury commercial"),[motion,setMotion]=useState("Cinematic"),[intensity,setIntensity]=useState(45),[negative,setNegative]=useState("warped product, distorted packaging, invented logo, fake text, duplicate product, melting, morphing, flicker, jitter, deformed hands, watermark, low quality"),[expanded,setExpanded]=useState(0),[history,setHistory]=useState([]),[job,setJob]=useState(null),fileRef=useRef(null);
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
 useEffect(()=>{let cancelled=false,objectUrl="";if(!video){setPlayableVideo("");return()=>{}};setPlayableVideo("");fetch(video,{mode:"cors"}).then(r=>{if(!r.ok)throw new Error("Video download failed");return r.blob()}).then(blob=>{if(cancelled)return;objectUrl=URL.createObjectURL(blob);setPlayableVideo(objectUrl)}).catch(()=>{if(!cancelled)setPlayableVideo(video)});return()=>{cancelled=true;if(objectUrl)URL.revokeObjectURL(objectUrl)}},[video]);
 const dims=aspect==="9:16"?{w:1080,h:1920}:{w:1920,h:1080};
 const shots=useMemo(()=>{const count=duration<=6?4:6;const base=Math.floor(duration/count),remainder=duration%count;return baseShots.slice(0,count).map((s,i)=>({...s,duration:base+(i<remainder?1:0)}))},[duration]);
 const onFile=e=>{const f=e.target.files?.[0];if(!f)return;setFile(f);setPreview(URL.createObjectURL(f));setPlan(null);setVideo("");setError("");setStatus("Product loaded — ready for director planning.")};
 const buildPlan=()=>{if(!file)return;setPlan({concept:brief,shots:shots.map(s=>({...s}))});setStatus("Director plan ready. Review the shots before generation.");setError("")};
 const makePreparedData=()=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{const maxW=aspect==="9:16"?720:960,maxH=aspect==="9:16"?1280:540;const c=document.createElement("canvas");const scale=Math.min(maxW/img.width,maxH/img.height,1);c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));const x=c.getContext("2d");x.fillStyle="#101014";x.fillRect(0,0,c.width,c.height);x.drawImage(img,0,0,c.width,c.height);let q=.76,data=c.toDataURL("image/jpeg",q);while(data.length>3500000&&q>.45){q-=.05;data=c.toDataURL("image/jpeg",q)}resolve(data)};img.onerror=reject;img.src=preview});
 const generate=async()=>{if(!file)return;setBusy(true);setError("");setVideo("");try{setStatus("Preparing validated reference frame…");const imageData=await makePreparedData();setStatus(`Reference frame prepared: ${dims.w} × ${dims.h} — ${aspect}.`);const payload={imageData,brief,aspect,duration,style,motion,intensity,negativePrompt:negative,shots:plan?.shots?.map(({name,action,camera,duration})=>({name,action,camera,duration}))||shots.map(({name,action,camera,duration})=>({name,action,camera,duration}))};const blob=await (await fetch(imageData)).blob();setStatus("Connecting to free Hugging Face GPU…");const app=await Client.connect("zerogpu-aoti/wan2-2-fp8da-aoti-faster",{events:["status","data"]});setStatus("Free GPU queue connected — generating fast 4-step video…");const submission=app.submit("/generate_video",{input_image:handle_file(blob),prompt:(brief+" "+selectedMotionText(style,motion,intensity)).slice(0,1800),steps:4,negative_prompt:negative,duration_seconds:2,guidance_scale:1,guidance_scale_2:1,seed:Math.floor(Math.random()*2147483647),randomize_seed:true});let result=null;for await(const event of submission){if(event.type==="status"){const st=event.stage||event.status?.stage||event.status;setStatus(st==="generating"?"Free GPU is rendering the video…":"Free GPU queue: "+String(st||"working")+"…")}if(event.type==="data"&&event.data)result=event.data}if(!result)throw new Error("Free GPU did not return a video.");const out=result[0]||result;const url=out?.url||out?.path||out?.video?.url||out?.video?.path;if(!url)throw new Error("Free GPU completed but returned no video URL.");setVideo(url);setStatus("AI film ready — generated on Hugging Face ZeroGPU.");setJob({requestId:"free-hf"});}catch(e){setError(e.message||"Something went wrong");setStatus("")}finally{setBusy(false)}};
 return <div className="app"><header><div className="brand"><div className="logo">M</div><div><b>Mira Studio</b><span>AI Product Film Director</span></div></div><div className="provider"><span className="dot"/>Wan 2.2 Fast • Free GPU</div></header>
 <main><section className="hero"><p className="eyebrow">DIRECT • GENERATE • REVIEW</p><h1>Turn one product image into a real AI commercial.</h1><p className="sub">Build a cinematic shot plan, validate the delivery frame, then generate multi-shot image-to-video footage.</p></section>
 <section className="workflow"><div className="step active"><b>01</b><span>Brief</span></div><div className="line"/><div className="step"><b>02</b><span>Director</span></div><div className="line"/><div className="step"><b>03</b><span>Generate</span></div><div className="line"/><div className="step"><b>04</b><span>Film</span></div></section>
 <section className="grid">
 <div className="card"><div className="cardhead"><span>01</span><h2>Product & creative brief</h2><button className="iconbtn" onClick={()=>setSettings(!settings)}><Settings2 size={17}/></button></div>
 <button className="drop" onClick={()=>fileRef.current.click()}>{preview?<img src={preview}/>:<><Upload size={28}/><b>Upload product photo</b><small>Plain isolated JPG, PNG or WebP</small></>}</button><input ref={fileRef} hidden type="file" accept="image/*" onChange={onFile}/>
 <textarea value={brief} onChange={e=>setBrief(e.target.value)}/>{settings&&<div className="advancedSettings"><div className="settings"><label>Visual style<select value={style} onChange={e=>setStyle(e.target.value)}><option>Luxury commercial</option><option>Minimal studio</option><option>Premium lifestyle</option><option>High-energy social ad</option><option>Editorial fashion</option><option>Futuristic tech</option></select></label><label>Motion language<select value={motion} onChange={e=>setMotion(e.target.value)}><option>Cinematic</option><option>Subtle</option><option>Dynamic</option><option>Product turntable</option><option>Macro / detail</option></select></label></div><div className="settings"><label className="rangeLabel">Motion intensity <b>{intensity}%</b><input type="range" min="0" max="100" value={intensity} onChange={e=>setIntensity(+e.target.value)}/></label><label>Aspect ratio<select value={aspect} onChange={e=>setAspect(e.target.value)}><option>9:16</option><option>16:9</option></select></label></div><div className="settings"><label>Film duration<select value={duration} onChange={e=>setDuration(+e.target.value)}><option value="5">5 sec • Fast</option><option value="6">6 sec</option><option value="8">8 sec</option><option value="10">10 sec</option><option value="12">12 sec</option><option value="15">15 sec</option></select></label><label>Output quality<select defaultValue="standard"><option>Standard • fast</option><option>High • slower</option></select></label></div><label className="negativeLabel">Negative prompt<input value={negative} onChange={e=>setNegative(e.target.value)}/></label></div>}
 <div className="framecheck"><Check size={15}/><span>Delivery frame: <b>{dims.w} × {dims.h}</b> • {aspect}</span></div>
 <button className="primary" disabled={!file||busy} onClick={buildPlan}><Sparkles size={18}/> {plan?"Refresh director plan":"Build director plan"}</button>
 </div>
 <div className="card"><div className="cardhead"><span>02</span><h2>Director shot plan</h2><span className="planmeta">{style} • {motion}</span></div>{plan?<div className="plan"><div className="planintro"><Clapperboard size={19}/><div><b>{plan.shots.length} shots • {duration}s total</b><p>Every shot has a distinct action and camera language.</p></div></div>{plan.shots.map((s,i)=><div className={"shot "+(expanded===i?"open":"")} key={s.name}><div className="num">{String(i+1).padStart(2,"0")}</div><div className="shotbody"><button className="shottoggle" onClick={()=>setExpanded(expanded===i?-1:i)}><span><b>{s.name}</b><small>{s.duration}s • {s.camera}</small></span>{expanded===i?<ChevronUp size={16}/>:<ChevronDown size={16}/>}</button>{expanded===i&&<div className="shotedit"><label>Action<textarea value={s.action} onChange={e=>{const n={...plan,shots:plan.shots.map((x,k)=>k===i?{...x,action:e.target.value}:x)};setPlan(n)}}/></label><label>Camera<select value={s.camera} onChange={e=>{const n={...plan,shots:plan.shots.map((x,k)=>k===i?{...x,camera:e.target.value}:x)};setPlan(n)}}>{cameraMoves.map(m=><option key={m}>{m}</option>)}</select></label></div>} </div></div>)}<div className="timeline">{plan.shots.map((s,i)=><button key={i} className={expanded===i?"active":""} style={{flex:s.duration}} onClick={()=>setExpanded(i)}>{i+1}</button>)}</div><button className="secondary" onClick={buildPlan}><WandSparkles size={16}/> Rebuild director plan</button></div>:<div className="empty"><Film size={35}/><p>No shot plan yet.</p><small>Upload a product and let Mira act as the director.</small></div>}</div>
 <div className="card stage"><div className="cardhead"><span>03</span><h2>AI generation</h2><div className="modeltag">Wan 2.2 Turbo • Fast</div></div><div className="preview">{video?<>{playableVideo?<video src={playableVideo} poster={preview} controls autoPlay loop muted playsInline preload="auto"/>:<div className="videoLoading">Loading generated video…</div>}<a className="videoOpen" href={video} target="_blank" rel="noreferrer">Open generated video</a></>:preview?<div className="sourcepreview"><img src={preview}/><span>Validated reference • {dims.w}×{dims.h}</span></div>:<div className="empty"><Film size={35}/><p>Final film preview</p><small>Your generated MP4 appears here. If preview does not load, use Open generated video.</small></div>}</div>
 <div className="actions"><button className="primary" disabled={!file||!plan||busy} onClick={generate}>{busy?<><Loader2 className="spin" size={18}/> {status||"Generating…"}</>:<><Play size={18}/> Generate AI film</>}</button>{video&&<a className="secondary" href={video} target="_blank" rel="noreferrer" download="mira-ai-film.mp4"><Download size={16}/> Save MP4</a>}</div>
 <div className="status">{status&&<><span className="statusdot"/>{status}</>}{job&&<span className="request">Request {job.requestId.slice(0,8)}…</span>}</div><div className="generationNotes"><span><Check size={13}/> Product consistency guard</span><span><Check size={13}/> Cinematic camera prompts</span><span><Check size={13}/> Negative prompt protection</span></div>{error&&<div className="error"><AlertTriangle size={16}/>{error}</div>}
 <p className="fineprint">Advanced director controls are sent with the generation request. Fast mode uses a public Hugging Face ZeroGPU Space. It is free to try but can have queue/rate limits and may change availability.</p>
 </div></section></main></div>}
createRoot(document.getElementById("root")).render(<App/>);